// constants.ts
export const DEPARTMENTS = [
  { value: 1, name: 'Management' },
  { value: 2, name: 'Customer Service' },
  { value: 3, name: 'Webdesign-On-site' },
  { value: 4, name: 'Booking-On-site' },
  { value: 5, name: 'Telemarketer-Off-site' },
  { value: 6, name: 'Telemarketer-Off-site' },
  { value: 7, name: 'Casting Exporter' },
  { value: 8, name: 'Verifier' },
  { value: 9, name: 'Telemarketer-On-site' },
  { value: 10, name: 'AccountExec' },
  { value: 11, name: 'Casting Miner' },
  { value: 12, name: 'Booking-Off-site' },
  { value: 13, name: 'Social Commenter' },
  { value: 14, name: 'Social Liker' },
  { value: 15, name: 'Social Poster' },
  { value: 16, name: 'Social Miner' },
  { value: 17, name: 'Sales Team-Lead' },
  { value: 18, name: 'CS  Team-Lead' },
  { value: 19, name: 'QA Department' },
]
